### ISSUE TITLE
zabbix proxy does not check

### ISSUE THREAD

**Issue by georg1ch** [dnaeon/py-vpoller#118]
Marin,

Need help, zabbix proxy does not check.
The module should be loaded and vpoller.so zabbix server and zabbix proxy
configuration files (server and proxy) vpoller.conf default
[proxy]
frontend = tcp: // *: 10123
backend = tcp: // *: 10124
mgmt = tcp: // *: 9999

[worker]
db = /var/lib/vconnector/vconnector.db
proxy = tcp: // localhost: 10124
mgmt = tcp: // *: 10000
helpers = vpoller.helpers.zabbix, vpoller.helpers.czabbix

Need to change the settings vpoller.conf?

thank you

**Comment by dnaeon** [comment]
Hey Sergey,

Have you updated the `zabbix_server.conf` and `zabbix_proxy.conf`files in order to load the `vpoller.so` module?

    ####### LOADABLE MODULES #######

    ### Option: LoadModulePath
    #       Full path to location of server modules.
    #       Default depends on compilation options.
    #
    # Mandatory: no
    # Default:
    LoadModulePath=/usr/local/lib/zabbix

    ### Option: LoadModule
    #       Module to load at server startup. Modules are used to extend functionality of the server.
    #       Format: LoadModule=<module.so>
    #       The modules must be located in directory specified by LoadModulePath.
    #       It is allowed to include multiple LoadModule parameters.
    #
    # Mandatory: no
    # Default:
    LoadModule=vpoller.so

When you update the config files for Zabbix Server & Proxy make sure to restart your services.

After that simply check in the logs and see whether the `vpoller.so` module has been loaded.

Let me know if you have any issues.

Thanks,
Marin

**Comment by georg1ch** [comment]
Marin,

I wrote above, the module should be loaded on vpooler.so Zabbix Server and Proxy:
2717: 20150126: 123717.058 using configuration file: /etc/zabbix/zabbix_proxy.conf
   2717: 20150126: 123717.067 Loading vPoller module configuration file /etc/zabbix/vpoller_module.conf
   2717: 20150126: 123717.067 loaded modules: vpoller.so

service zabix-server and zabbix-proxy restarted after the update config files

Thanks

**Comment by dnaeon** [comment]
Ah, I guess I misunderstood the issue you are having.

So, you have `vpoller.so` module loaded by your Zabbix Server & Proxy successfully.

What is the issue that you are having now, because it is not clear to me what issue you are having? 

Thanks,
Marin

**Comment by georg1ch** [comment]
Zabbix Proxy does not check vSphere.
In the log file vpoller-worker.log on Zabbix Proxy except that he started, any more what is not. No checks.

**Comment by dnaeon** [comment]
Okay, that seems like your vPoller requests are not arriving at your vPoller Proxy.

By default the Zabbix Server & Proxy module for vPoller will send vPoller requests to `tcp://127.0.0.1:10123` endpoint, where it would expect to find a vPoller Proxy with any connected vPoleler Workers to it, so that new tasks can be processed.

Is your vPoller Proxy running on the same machine as the Zabbix Proxy is running? If that is the case then no further configuration is needed, except that you need to make sure that vPoller Workers are actually connecting to that vPoller Proxy.

If your vPoller Proxy is running outside Zabbix Proxy, then you need to tell the Zabbix vPoller module to which endpoint new requests will be sent.

Let's say that you have 4 VMs, each of them is running one of the vPoller/Zabbix services, for example:

1. You have a Zabbix Server system called `zabbix-server.example.org`
2. You have a Zabbix Proxy system called `zabbix-proxy.example.org`
3. Your vPoller Proxy is running at `vpoller-proxy.example.org`
4. Your vPoller Worker is running at `vpoller-worker.example.org`

You could be running the vPoller Proxy & Worker on any of the Zabbix Server or Proxy servers, but let's say that these are 4 different VMs, just to illustrate how things should be configured.

Since by default the `vpoller.so` module as loaded by Zabbix Server and Zabbix Proxy will use a default endpoint `tcp://127.0.0.1:10123` that means that when Zabbix Server/Proxy tries to talk to vPoller it will fail, because your vPoller Proxy is at `tcp://vpoller-proxy.example.org:10123`.

In order to point your Zabbix Server/Proxy to use a different vPoller endpoint you should create a `/etc/zabbix/vpoller_module.conf` file on `zabbix-server.example.org` and `zabbix-proxy.example.org` and set the `vPollerProxy` config entry to your correct vPoller Proxy, e.g. `tcp://vpoller-proxy.example.org:10123`.

Check this example configuration file for configuring the `/etc/zabbix/vpoller_module.conf` file.

* https://github.com/dnaeon/py-vpoller/blob/master/extra/zabbix/vpoller-module/vpoller_module.conf.sample

And here is a completely working configuration files for the example setup described above.

`/etc/vpoller/vpoller.conf` as configured on `vpoller-proxy.example.org`, `vpoller-worker.example.org`:

```ini
[proxy]
frontend = tcp://vpoller-proxy.example.org:10123
backend  = tcp://vpoller-proxy.example.org:10124
mgmt     = tcp://*:9999
   
[worker]
db       = /var/lib/vconnector/vconnector.db
proxy    = tcp://vpoller-proxy.example.org:10124
mgmt     = tcp://*:10000
```

And this is how `/etc/zabbix/vpoller_module.conf` would look like on `zabbix-server.example.org` and `zabbix-proxy.example.org`:

```ini
# This is the configuration file for the vPoller loadable module.
# For more information about vPoller,
# please visit https://github.com/dnaeon/py-vpoller

### Option: vPollerTimeout
#    Specifies the timeout period for vPoller task requests.
#    The timeout value is in milliseconds.
#
# Mandatory: no
# Range: 1000-60000
# Default:
# vPollerTimeout=10000

### Option: vPollerRetries
#    Specifies how many times a vPoller task requests can be retried.
#
# Mandatory: no
# Range: 1-100
# Default:
# vPollerRetries=1

### Option: vPollerProxy
#    Specifies the vPoller Proxy endpoint to which new
#    task requests will be sent.
#
# Mandatory: no
# Default:
vPollerProxy=tcp://vpoller-proxy.example.org:10123
```

Regards,
Marin

**Comment by georg1ch** [comment]
Marin, thanks, it worked
about this file vpoller_module.conf I forgot :)
More prompt, you can specify it on several proxies Zabbix Server and Proxy?
For Example:

vPollerProxy = tcp: //vpoller-proxy1.example.org: 10123, vPollerProxy = tcp: //vpoller-proxy2.example.org: 10123
OR
vPollerProxy = tcp: //vpoller-proxy1.example.org: 10123
vPollerProxy = tcp: //vpoller-proxy2.example.org: 10123

Regards,
Sergey

**Comment by dnaeon** [comment]
Currently `vPollerProxy` should contain just a single endpoint to your vPoller Proxy.

The vPoller Proxy will load balance requests between all connected vPoller Workers, so no need for multiple vPoller Proxy entries for now.

In future vPoller releases probably will be added support to provide more than one vPoller Proxy, which will be good for consuming tasks from multiple endpoints.

Glad to hear it is working now, closing ticket. :)

Thanks,
Marin
