### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by georg1ch** [dnaeon/py-vpoller#122]
When monitoring all analyzing processes I run into the vSphere vCenter performance
CPU should be loaded to 100%
Growing queue.
and the log files zabbix_server.log see here these errors:
Did not receive response from vPoller, giving up.
vCenter (vcpu 4, mem 8Gb)
ESXi 96
VMs> 1000
When vPoller work load on the CPU vCenter 99.17%
Without load 5% vPoller

2 VMs (vcpu 8, mem 8Gb, cpu load 50%) running with: vpoller-worker -c 32
1 VM - it zabbix server and vPoller Proxy

Zabbix items:
Number of hosts (enabled / disabled / templates) 1307 1283/0/24
Number of items (enabled / disabled / not supported) 38366 37720/0/646
Number of triggers (enabled / disabled [problem / ok]) 4385 4385/0 [155/4230]

vconnector
vpoller-proxy: vc1, esxi1-10
vpoller-worker1: vc1, esxi11-20
vpoller-worker2: vc1, esxi21-30

**Comment by dnaeon** [comment]
On your vPoller Worker VMs you are running with 32 worker processes, while you have only 8 cores on them, which is going to cause more issues than solve ones.

Generally you should be running worker processes equal to the number of CPUs you have on the VM, e.g. 8 vCPUs = 8 Worker process.

If you remove the `--concurrency 32` option to vPoller Worker, your workers should start up with the number of cores you have, so you can remove it for now.

On how many VMs are you running vPoller Workers? Can you deploy another VM, install vPoller on it and start another vPoller Worker there connected to the same vPoller Proxy?

How many items are being delayed and for how long?

Thanks,
Marin

**Comment by georg1ch** [comment]
option --concurrent 32 deleted
launched another 2 VM
queue at 1:30:

![vsphere monitoring_ queue refreshed every 30 sec - google chrome 2015-01-28 17 28 40](https://cloud.githubusercontent.com/assets/10630124/5939278/6cc8802c-a713-11e4-84ab-bc5619a48422.png)

**Comment by dnaeon** [comment]
That is a lot of delayed items...

Can you check whether your vCenter is swapping? I've had a similar issue before where items were being delayed because of insufficient memory on the vCenter server and it was swapping.

Bumping the memory on the vCenter fixed all my issues.

Can you please check that? 

Thanks,
Marin

**Comment by georg1ch** [comment]
In the near future the memory on the server will increase.
Write the result.

Thanks,
Sergey

**Comment by dnaeon** [comment]
Hey Sergey,

Just to let you know that I'm working on getting a cache feature implemented for vConnector (the vSphere connector interface that vPoller uses) and that should speed things a lot and also reduce the number of API calls to the vCenter server.

I should be able to get that implemented soon, so I will let you know soon enough, so that you can test it.

Thanks,
Marin

**Comment by georg1ch** [comment]
Thanks

**Comment by georg1ch** [comment]
Marin,

I see that there is a new version vconnector 0.3.3
Should I try it?

Regards,
Sergey

**Comment by dnaeon** [comment]
Hey Sergey,

I just need to test a few more things and then you can go ahead with the new vConnector release.

Please wait until I commit and push all my new changes before you test it out.

I will let you know when I'm ready very soon.

Thanks,
Marin

**Comment by dnaeon** [comment]
Hey Sergey,

I've just pushed my commits with the latest changes in vPoller and vConnector.

Could you please upgrade vConnector to version `0.3.5` and vPoller to version `0.3.9-dev`?

You can do that by either installing vConnector and vPoller from the Github repos or by using `pip(1)`.

When you upgrade vPoller and vConnector make sure to do the necessary changes to your `vpoller.conf` file in order to load the vSphere tasks and also to enable caching of vSphere managed objects.

Check the documentation for the new configuration options that need to be added to your `vpoller.conf` file:

* http://vpoller.readthedocs.org/en/latest/configuration.html

Let me know how it goes.

Thanks,
Marin

**Comment by dnaeon** [comment]
Sergey,

Any progress with the latest versions of vConnector an vPoller?

Thanks,
Marin

**Comment by georg1ch** [comment]
Marin,
now engaged in updating and testing

The result will write

Regards,
Sergey

**Comment by georg1ch** [comment]
Marin,
fine, everything works as it should.
First queue checks increased, but the passage of time everything was fine.
vCenter cpu now nashruzhen by ~ 60%
Queue is not growing.

Regards,
Sergey

**Comment by dnaeon** [comment]
Great news! :) 

Thanks for testing and confirming this! :)

I will close this issue then, feel free to re-open it or submit a separate one in case you are having any performance issues.

Thanks,
Marin

**Comment by georg1ch** [comment]
Hi Marin,
after the upgrade queue stopped growing, but the load on the vCenter CPU avg 92%
this inconvenience in the management infrastructure.
Increase in Number of vpoller-worker can reduce the load on the vCenter?

Regards,
Sergey

**Comment by dnaeon** [comment]
Hey Sergey,

Are you running the Linux Appliance of vCenter and what version is it?

Have you increased the number of vCPUs and memory on it?

According to the vCenter 5.5 Best Practices you should increase your memory to at least 16GB for a  deployment of your size.

* http://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2052334

Please check the above KB and do the needed changes in order to meet the minimum requirements for your environment.

Thanks,
Marin

**Comment by georg1ch** [comment]
vCenter 5.1 windows ver.
4 vCPU
RAM 16 GB

**Comment by dnaeon** [comment]
So, you have upgraded the memory already?

Because you initially mentioned that this is a 8GB vCenter.

> vCenter (vcpu 4, mem 8Gb)
> ESXi 96
> VMs> 1000

https://github.com/dnaeon/py-vpoller/issues/122#issue-55750482

Can you check which process is causing the load? I would guess it's vpxd, but just in case please check that.

Another thing that you might consider is disabling some of the items which you don't need.

Regards,
Marin

**Comment by georg1ch** [comment]
I increased the RAM on the vCenter up to 16GB
CPU load process vpxd
Some items I check disabled.

Regards,
Sergey
