### ISSUE TITLE
Invalid Key Format When Using host.perf.metric.get on Zabbix

### ISSUE THREAD

**Issue by jjahns** [dnaeon/py-vpoller#147]
So I'm receiving the following message when trying to test this item:

zabbix_agentd -t vpoller[host.perf.metric.get,vc,esxi,value,,,,149,,]
vpoller[host.perf.metric.get,vc,esxi,value,,,,149,,] [m|ZBX_NOTSUPPORTED] [Unsupported item key.]

Using quotes does not work either.  

I can use the vpoller-client to get this information just fine.  It's just that this won't work at all.

**Comment by dnaeon** [comment]
Hey,

The performance counter related items have been updated, so now instead of the using the `counter id` (e.g. 149) you need to specify the full counter name, e.g. `net.usage.kiloBytesPerSecond.average`.

Make sure to check this documentation:

* http://vpoller.readthedocs.org/en/latest/examples.html#performance-metrics

Thanks,
Marin
