### ISSUE TITLE
[Question] Is it possible to get the properties of an individual object

### ISSUE THREAD

**Issue by rreubenur** [dnaeon/py-vpoller#205]
I have a VM Object and I want to poll some of it's properties.  I don't want to build a container view. The ```collect_properties()``` method that you have written, it takes the contanerView as argument for ```ObjectSpec().obj``` .

I tried passing directly the VM object for ```ObjectSpec().obj``` . But it is failing in the line ``` collector.RetrieveContents([filter_spec]) ``` .

Kindly let me know that it is possible to pass a vm object to get it's property or not without creating a container view ?

Thanks,
Reuben

**Comment by dnaeon** [comment]
Hey Reuben,

Can you provide the complete code, so I can better understand what exactly you are trying to do? 

Are you intending on using vPoller/vConnector standalone and you are just curious how to get some properties for a single object? If that's the case, then simply find the object you are interested and access it's properties directly.

**Comment by rreubenur** [comment]
Hey Thanks @dnaeon  for your reply. I have mistakenly posted in vPoller instead of vConnector. My question is specific to the method ```collect_properties()```

As you know that the clone method returns the newly created VM object. Now If I want to access any property of that VM object. I have to use ```.``` . 

i.e ```vm.name``` or  ```vm.guest.ipAddress```  etc . But I don't want to do that. I want to collect few properties of that object only.

Now If I use ```collect_properties()``` method to get the properties I have to build a ```view_ref``` of ```vim.VirtualMachine``` using the method ```get_container_view()``` which is nothing but the list of all the vms in the container. And I have to again search for the specific vm that I want.

My intention is that, Instead of passing a ```view_ref``` I want to pass the vm object directly. So that I don't have to search my VM in the list of all vms.

Let me know If I'm not clear.

Thanks,
Reuben

**Comment by dnaeon** [comment]
Correct, `collect_properties()` method expects to have a view reference to work on. If I'm understanding you correctly, what you want to do is to use the already returned `VirtualMachine` object after a successful clone operation and simply use that to collect properties, but don't want to go over whole process of creating a new view by searching for the VM object you already have?

What you can do instead of simply wrap your new object in a `ListView` and pass it to `collect_properties()`, like this.

```python
view_ref = agent.get_list_view([my_new_obj])
```

And then just pass the view to `collect_properties`. Remember to destroy the view once done with it.

If that's not what you meant, please provide some code, so I can better understand what you want to do.

Thanks,
Marin

**Comment by rreubenur** [comment]
Thank you very much ! This is exactly what I need.  ```get_list_view()``` was the crux.
